# Generated by Django 4.2.1 on 2023-05-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dictation_delete_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dictation',
            name='sentence',
            field=models.TextField(verbose_name='内容'),
        ),
        migrations.AlterField(
            model_name='dictation',
            name='sound_file_path',
            field=models.TextField(verbose_name='音声ファイルのパス'),
        ),
    ]
