# Generated by Django 4.2.1 on 2023-05-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dictation_sentence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictation',
            name='rank',
            field=models.PositiveIntegerField(default=0, verbose_name='難易度'),
        ),
    ]
