# Generated by Django 4.2.1 on 2023-05-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_dictation_rank'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dictation',
            name='sentence',
        ),
        migrations.AddField(
            model_name='dictation',
            name='english_sentence',
            field=models.TextField(default='English Sentence', verbose_name='英文'),
        ),
        migrations.AddField(
            model_name='dictation',
            name='japanese_sentence',
            field=models.TextField(default='日本語訳', verbose_name='日本語訳'),
        ),
    ]
